[project]
name = "cerbos-sdk-python"
version = "0.1.0"
description = "SDK for working with Cerbos: an open core, language-agnostic, scalable authorization solution"
authors = [
    {name = "Cerbos Developers", email = "help+python@cerbos.dev"},
]
license-expression = "Apache-2.0"
dependencies = [
    "requests>=2.27.1",
    "dataclasses-json>=0.5.7",
    "requests-toolbelt>=0.9.1",
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://cerbos.dev"

[project.optional-dependencies]
[tool.pdm]
[tool.pdm.dev-dependencies]
lint = [
    "black>=22.3.0",
    "pylint>=2.13.5",
    "isort>=5.10.1",
    "mypy>=0.942",
    "types-requests>=2.27.16",
]
tools = []

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[tool.pyprojectx]
pdm = "pdm==1.13.6"
black = "black"
pylint = "pylint"
mypy = "mypy"

[tool.pyprojectx.aliases]
install = "pdm install"
run = "pdm run"
outdated = "pdm update --outdated"
test = "pdm run pytest"
black = "black cerbos tests"
pylint = "pylint cerbos tests"
mypy = "mypy cerbos tests"

[tool.pyright]
extraPaths = ["__pypackages__/3.10/lib/"]

[tool.mypy]
python_version = "3.8"
